import Head from "next/head";

import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Henry Meds</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            top: "50%",
            height: "100vh",
          }}
        >
          <Link href="/provider">
            <button style={{ color: "orange", marginRight: "10px" }}>
              Provider
            </button>
          </Link>
          <Link href="/client">
            <button style={{ color: "pink" }}>Client</button>
          </Link>
        </div>
      </main>
    </>
  );
}
